# Generated by Django 3.2.12 on 2022-06-23 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='Username')),
                ('email', models.EmailField(help_text=False, max_length=254, unique=True, verbose_name='Email')),
                ('image', models.ImageField(default='/media/default.jpg', upload_to='images/% Y/% m/% d/', verbose_name='Image')),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('miss', 'Miss'), ('dr', 'dr.'), ('Dr', 'Dr.')], default='mr', max_length=10, verbose_name='Title')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Gender')),
                ('employee', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default=1, verbose_name='Employee')),
                ('first_date_range', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='First Date')),
                ('last_date_range', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last Date')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Province/State')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('zip', models.CharField(blank=True, max_length=100, verbose_name='Zip Code')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=255, verbose_name='Fax')),
                ('mobile', models.CharField(blank=True, max_length=255, verbose_name='Mobile')),
                ('vat', models.CharField(blank=True, max_length=15, verbose_name='VAT Number')),
                ('website', models.CharField(blank=True, max_length=254, verbose_name='Website')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-username',),
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text=False, max_length=20, unique=True, verbose_name='Nome do Usuário')),
                ('contacto', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text=False, max_length=128, null=True, region=None, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, help_text=False, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, help_text=False, verbose_name='Sexo')),
                ('terms', models.BooleanField(help_text=False, verbose_name='Termos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
