# Generated by Django 3.2.12 on 2022-06-24 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_date_range',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_date_range',
        ),
        migrations.AddField(
            model_name='user',
            name='first_active_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='First Active Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last Active Date'),
        ),
    ]
