# Generated by Django 3.2.12 on 2022-06-24 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_last_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 24, 0, 49, 32, 966462), verbose_name='Last Active Date'),
        ),
    ]
