# Generated by Django 3.2.12 on 2022-06-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/media/default.jpg', upload_to='images/% Y/% m/% d/', verbose_name='Image'),
        ),
    ]
