# Generated by Django 3.2.12 on 2022-07-03 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_last_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 3, 16, 16, 18, 601700), verbose_name='Last Active Date'),
        ),
    ]
