# Generated by Django 3.2.12 on 2022-07-04 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_user_last_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 4, 13, 59, 50, 98141), verbose_name='Last Active Date'),
        ),
    ]
