# Generated by Django 3.2.12 on 2022-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='origin',
            field=models.CharField(default='Costumer Invoice', max_length=20),
        ),
    ]
