# Generated by Django 3.2.12 on 2022-06-24 17:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_userwarehouse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwarehouse',
            unique_together={('user', 'warehouse')},
        ),
    ]
