BBBBBBB BBBBBBBBBBB

BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB  X XXXXXXX BBBBBBBB BBBBB

BBBBB BBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX 
            XXXX XXXXXXXXXXXX XXXXXXXXX 
            XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX   
                XXXX  gettext(u'PLEASE, LOGIN TO CONTINUE')  XXXXX
                XXXX    
                BBBBBBBBBB
                BBBBBB BBBB

                XXXX gettext(u"Don't have account?")   XX XXXXXXBBB BBBBBBBBBBBBBBBBXX 
                     gettext(u'Register')  XXXX XXXXX
            
        XXXXXX
    XXXXXX

BBBBBBBB BBBBBB

