BBBBBBB BBBBBBBBBBB

BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB  X  gettext(u'Login')  BBBBBBBB BBBBB

BBBBB BBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX 
            XXXX XXXXXXXXXXXX XXXXXXXXX 
            XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX   
                XXXX  gettext(u'PLEASE, SIGN UP')  XXXXX
                XXXX    
                BBBBBBBBBB
                BBBBBB BBBB

                XXXX gettext(u'Already Have account?')   XX XXXXXXBBB BBBBBBBBBBBBBXX 
                     gettext(u'Please Login')  XXXX XXXXX
            XXXXXX
        XXXXXX
    XXXXXX

BBBBBBBB BBBBBB

