# Generated by Django 2.2.7 on 2022-03-16 20:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='Name of the Branch, Department, etc', max_length=100, verbose_name='Branch Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('branch_name',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the Company, Department, etc', max_length=100, verbose_name='Company Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('company_contacts', models.CharField(blank=True, max_length=255)),
                ('company_manager', models.CharField(blank=True, max_length=100)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_system_no', models.IntegerField(verbose_name='System no')),
                ('component_name', models.CharField(max_length=100, verbose_name='Component Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('component_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Manufacturer')),
                ('component_stock_code', models.CharField(blank=True, max_length=100, verbose_name='Stock Code')),
                ('component_image', models.ImageField(default='default.jpeg', upload_to='images/% Y/% m/% d/', verbose_name='Image')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'ordering': ('component_name',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Group')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_name', models.CharField(max_length=50)),
                ('maintenance_type', models.IntegerField(choices=[(1, 'Routine'), (2, 'Preventive'), (3, 'Corrective'), (4, 'Predective')], default=1)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('maintenance_schedule', models.IntegerField(choices=[(1, 'Hours'), (2, 'Days'), (3, 'Months'), (4, "KM's")], default=1)),
                ('maintenance_frequency', models.IntegerField(default=0)),
                ('time_allocated', models.FloatField(default=0)),
                ('maintenance_action', models.CharField(max_length=255)),
                ('item_used', models.CharField(max_length=20)),
                ('quantity', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ('maintenance_name',),
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=50, verbose_name='System')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Type')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.System')),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype_name', models.CharField(max_length=50, verbose_name='Subtype')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(help_text='Name of the Position, Department, etc', max_length=100, verbose_name='Position Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.Branch')),
            ],
            options={
                'ordering': ('position_name',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('maintenance_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.Maintenance')),
            ],
            options={
                'ordering': ('schedule_name',),
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(help_text='Name of the Division, Department, etc', max_length=100, verbose_name='Division Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('division_address', models.CharField(blank=True, max_length=255)),
                ('division_contacts', models.CharField(blank=True, max_length=255)),
                ('division_manager', models.CharField(blank=True, max_length=100)),
                ('division_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.Company')),
            ],
            options={
                'ordering': ('division_name',),
            },
        ),
        migrations.CreateModel(
            name='ComponentAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_serial_number', models.CharField(max_length=50, verbose_name='Component Serial No.')),
                ('component_status', models.IntegerField(choices=[(1, 'Good'), (0, 'Broken')], default=1, verbose_name='Component Status')),
                ('component_image', models.ImageField(default='default.jpeg', upload_to='images/% Y/% m/% d/', verbose_name='Image')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_allocated', models.DateTimeField(default=django.utils.timezone.now)),
                ('depreciation', models.FloatField(default=0, verbose_name='Depreciation %')),
                ('start_value_hours', models.FloatField(default=0, verbose_name='Start Value (Hours)')),
                ('start_value_years', models.FloatField(default=0, verbose_name='Start Value (Years)')),
                ('start_value_milliege', models.FloatField(default=0, verbose_name='Start Value (KM)')),
                ('garrantee_value_hours', models.FloatField(default=0, verbose_name='Warrantee Value (Hours)')),
                ('garrantee_value_years', models.FloatField(default=0, verbose_name='Warrantee Value (Years)')),
                ('garrantee_milliege', models.FloatField(default=0, verbose_name='Warrantee Milliege (KM)')),
                ('end_of_life_hours', models.FloatField(default=0, verbose_name='End of Life (Hours)')),
                ('end_of_life_years', models.FloatField(default=0, verbose_name='End of Life (Years)')),
                ('end_of_life_milliege', models.FloatField(default=0, verbose_name='End of Life (KM)')),
                ('warn_before_hours', models.FloatField(default=0, verbose_name='Warn Before (Hours)')),
                ('warn_before_years', models.FloatField(default=0, verbose_name='Warn Before (Years)')),
                ('warn_before_milliege', models.FloatField(default=0, verbose_name='Warn Before (KM)')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Branch')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Company')),
                ('component_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Component', verbose_name='component Name')),
                ('division_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Division')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.Group')),
                ('position_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Position')),
                ('subtype_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.SubType')),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.System')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.Type')),
            ],
            options={
                'verbose_name_plural': 'Components Allocation',
                'ordering': ('-date_allocated',),
            },
        ),
        migrations.AddField(
            model_name='component',
            name='maintenance_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.MaintenanceSchedule'),
        ),
        migrations.AddField(
            model_name='branch',
            name='division_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.Division'),
        ),
    ]
