# Generated by Django 2.2.7 on 2022-03-09 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('asset_serial_no', models.CharField(max_length=100)),
                ('asset_manufacturer', models.CharField(max_length=100)),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset_issued', models.BooleanField(default=False)),
                ('asset_image', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category_image', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('parent_location', models.IntegerField(choices=[(0, '---')], default=0)),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('location_contacts', models.CharField(blank=True, max_length=255)),
                ('location_manager', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('system_image', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsIssuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_status', models.BooleanField(default=True)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('asset_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Assets')),
                ('asset_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Location')),
            ],
            options={
                'verbose_name_plural': 'Asset Issuances',
            },
        ),
        migrations.AddField(
            model_name='assets',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Category'),
        ),
        migrations.AddField(
            model_name='assets',
            name='system_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.System'),
        ),
    ]
