# Generated by Django 2.2.7 on 2022-03-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent_location',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Secutec Mozambique, Lda')], default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
