# Generated by Django 2.2.7 on 2022-03-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_auto_20220309_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'ordering': ('asset_name',), 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetsissuance',
            options={'ordering': ('-date_issued',), 'verbose_name_plural': 'Asset Issuances'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('location_name',)},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ('system_name',)},
        ),
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
