# Generated by Django 3.2.12 on 2022-03-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='item_used',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='quantity',
        ),
    ]
