# Generated by Django 2.2.7 on 2022-03-07 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_assetsissuance_asset_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('parent_location', models.CharField(choices=[('0', '---')], max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='assets',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='assets',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetsissuance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='assetsissuance',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='assets',
            name='asset_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Location'),
        ),
    ]
