# Generated by Django 2.2.7 on 2022-03-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_auto_20220316_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'ordering': ('schedule_name',), 'verbose_name_plural': 'Maintenance Schedules'},
        ),
    ]
