# Generated by Django 3.2.12 on 2022-04-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0003_auto_20220331_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='item',
            name='maintenance',
            field=models.ManyToManyField(to='asset_app.Maintenance'),
        ),
    ]
