# Generated by Django 3.2.12 on 2022-03-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0003_auto_20220316_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtype',
            options={'verbose_name_plural': 'Subtypes'},
        ),
    ]
