# Generated by Django 2.2.7 on 2022-03-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0004_auto_20220307_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='parent_location',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Porto de Pesca'), (2, 'Departamento de Financas')], max_length=50),
        ),
    ]
