# Generated by Django 2.2.7 on 2022-03-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0004_auto_20220309_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_name',
            field=models.CharField(max_length=100, verbose_name='Asset Name'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.IntegerField(choices=[(1, 'Good'), (0, 'Broken')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='system_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.System', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(help_text='Name of the Company, Department, etc', max_length=100, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='System Name'),
        ),
    ]
