# Generated by Django 3.2.12 on 2022-04-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0004_auto_20220407_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='maintenance',
            field=models.ManyToManyField(related_name='maintenances', to='asset_app.Maintenance'),
        ),
    ]
