# Generated by Django 3.2.12 on 2022-03-17 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0004_alter_subtype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(help_text='Name of the Vendor, Department, etc', max_length=100, verbose_name='Vendor Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('vendor_address', models.CharField(blank=True, max_length=255)),
                ('vendor_contacts', models.CharField(blank=True, max_length=255)),
                ('vendor_manager', models.CharField(blank=True, max_length=100)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'ordering': ('vendor_name',),
            },
        ),
        migrations.AddField(
            model_name='componentallocation',
            name='vendor_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset_app.vendor', verbose_name='Vendor Name'),
            preserve_default=False,
        ),
    ]
