# Generated by Django 3.2.12 on 2022-04-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0005_alter_item_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Quantity'),
        ),
    ]
