# Generated by Django 2.2.7 on 2022-03-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0005_auto_20220308_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='parent_location',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Porto de Pesca'), (2, 'Departamento de Financas')]),
        ),
    ]
