# Generated by Django 3.2.12 on 2022-03-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0005_auto_20220318_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentallocation',
            name='component_image',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='images/% Y/% m/% d/', verbose_name='Image'),
        ),
    ]
