# Generated by Django 2.2.7 on 2022-03-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0005_auto_20220309_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsissuance',
            name='asset_status',
        ),
        migrations.AlterField(
            model_name='assets',
            name='asset_issued',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.IntegerField(choices=[(1, 'Good'), (0, 'Broken')], default=1, verbose_name='Asset Status'),
        ),
    ]
