# Generated by Django 3.2.12 on 2022-04-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0006_alter_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='maintenance',
        ),
    ]
