# Generated by Django 2.2.7 on 2022-03-09 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0006_auto_20220309_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset_assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Choose the Location'),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Assets', verbose_name='Choose Asset'),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Location', verbose_name='Choose the Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent_location',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Secutec Mozambique, Lda')], default=0, verbose_name='Parent Location (if Any)'),
        ),
        migrations.AlterField(
            model_name='system',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Category', verbose_name='Category'),
        ),
    ]
