# Generated by Django 2.2.7 on 2022-03-09 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0007_auto_20220309_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset_assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Choose the Assignee'),
        ),
    ]
