# Generated by Django 2.2.7 on 2022-03-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0008_auto_20220309_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='status',
            new_name='asset_status',
        ),
    ]
