# Generated by Django 3.2.12 on 2022-04-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0008_maintenanceitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceitem',
            options={'verbose_name_plural': 'Maintenance Items'},
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceitem',
            unique_together={('maintenance', 'item')},
        ),
    ]
