# Generated by Django 3.2.12 on 2022-04-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0009_auto_20220407_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.item'),
        ),
        migrations.AlterField(
            model_name='maintenanceitem',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.maintenance'),
        ),
    ]
