# Generated by Django 2.2.7 on 2022-03-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0009_auto_20220309_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='asset_serial_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
