# Generated by Django 2.2.7 on 2022-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0010_auto_20220309_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_status',
            field=models.IntegerField(choices=[(1, 'Good'), (0, 'Broken'), (0, 'Broken')], default=1, verbose_name='Asset Status'),
        ),
    ]
