# Generated by Django 3.2.12 on 2022-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0011_auto_20220415_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='time_schedule',
            field=models.IntegerField(choices=[(1, 'Hours'), (2, 'Days'), (3, 'Months'), (4, "KM's")], default=1),
        ),
    ]
