# Generated by Django 2.2.7 on 2022-03-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0011_auto_20220309_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='parent_location',
            field=models.IntegerField(choices=[(0, 'No Parent')], default=0, verbose_name='Parent Location (if Any)'),
        ),
    ]
