# Generated by Django 2.2.7 on 2022-03-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0012_auto_20220310_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsissuance',
            options={'ordering': ('-date_issued',), 'verbose_name_plural': 'Assets Issuance'},
        ),
    ]
