# Generated by Django 3.2.12 on 2022-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0012_maintenance_time_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='schedule',
            field=models.CharField(choices=[(1, 'Hours'), (2, 'Days'), (3, 'Months'), (4, "KM's")], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='time_schedule',
            field=models.CharField(choices=[(1, 'Hours'), (2, 'Days'), (3, 'Months'), (4, "KM's")], default=1, max_length=10),
        ),
    ]
