# Generated by Django 2.2.7 on 2022-03-10 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0013_auto_20220310_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset_assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Assets', verbose_name='Asset Name'),
        ),
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.Location', verbose_name='Location of Asset'),
        ),
    ]
