# Generated by Django 3.2.12 on 2022-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0013_auto_20220415_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='schedule',
            field=models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Months', 'Months'), ('KM', "KM's")], default='Hours', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='time_schedule',
            field=models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Months', 'Months'), ('KM', "KM's")], default='Hours', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(choices=[('Routine', 'Routine'), ('Preventive', 'Preventive'), ('Corrective', 'Corrective'), ('Predective', 'Predective')], default='Routine', max_length=15),
        ),
    ]
