# Generated by Django 3.2.12 on 2022-04-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0014_auto_20220415_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocation_no',
            field=models.IntegerField(unique=True, verbose_name='Allocation No.'),
        ),
    ]
