# Generated by Django 3.2.12 on 2022-04-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0015_alter_allocation_allocation_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Broken', 'Broken')], default='Good', max_length=15, verbose_name='Status'),
        ),
    ]
