# Generated by Django 3.2.12 on 2022-04-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_app', '0016_alter_allocation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('cell', models.CharField(blank=True, max_length=255, verbose_name='Cell')),
                ('telephone', models.CharField(blank=True, max_length=255, verbose_name='Telephone')),
                ('fax', models.CharField(blank=True, max_length=255, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('web', models.CharField(blank=True, max_length=255, verbose_name='Web Site')),
                ('logo', models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='Logo')),
                ('logo_square', models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='Logo Square')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MaintenanceSchedule',
        ),
    ]
