# Generated by Django 3.2.12 on 2022-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0017_auto_20220416_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'ordering': ('name',), 'verbose_name': 'Company Settings', 'verbose_name_plural': 'Companies Settings'},
        ),
        migrations.AddField(
            model_name='companysettings',
            name='cell_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cell 2'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Company Name'),
        ),
    ]
