# Generated by Django 3.2.12 on 2022-04-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0020_rename_companysettings_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ('name',), 'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
    ]
