# Generated by Django 3.2.12 on 2022-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0021_alter_settings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
