# Generated by Django 3.2.12 on 2022-04-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0023_allocation_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='QrCode'),
        ),
    ]
