# Generated by Django 3.2.12 on 2022-04-19 20:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_app', '0024_alter_allocation_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='date_allocated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900)),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900)),
        ),
        migrations.AlterField(
            model_name='branch',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 353390), editable=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 353390), editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 348214), editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 348214), editable=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 348214), editable=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 348214), editable=False),
        ),
        migrations.AlterField(
            model_name='division',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 352353), editable=False),
        ),
        migrations.AlterField(
            model_name='division',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 352353), editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 353390), editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 353390), editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 361940), editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 361940), editable=False),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 348214), editable=False),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 348214), editable=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 353390), editable=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 353390), editable=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 348214), editable=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 348214), editable=False),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 356900), editable=False),
        ),
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('start', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 361940))),
                ('end', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 361940))),
                ('duration', models.IntegerField(default=1)),
                ('warn_before', models.IntegerField(default=7)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Finished', 'Finished'), ('Abandoned', 'Abandoned')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 361940), editable=False)),
                ('date_modified', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 20, 7, 48, 361940), editable=False)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.allocation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
