# Generated by Django 3.2.12 on 2022-04-19 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_app', '0026_auto_20220419_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceorder',
            name='duration',
        ),
        migrations.AlterField(
            model_name='maintenanceorder',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.allocation', verbose_name='Allocation'),
        ),
        migrations.AlterField(
            model_name='maintenanceorder',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='maintenanceorder',
            name='order',
            field=models.IntegerField(unique=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='maintenanceorder',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Person in Charge'),
        ),
        migrations.AlterField(
            model_name='maintenanceorder',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
    ]
