# Generated by Django 3.2.12 on 2022-04-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0028_auto_20220419_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
