# Generated by Django 3.2.12 on 2022-04-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0029_workorder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='progress',
            field=models.FloatField(default=0, verbose_name='Work Progress'),
        ),
    ]
