# Generated by Django 3.2.12 on 2022-04-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0034_auto_20220420_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Finished', 'Finished'), ('Abandoned', 'Abandoned')], default='Pending', max_length=15),
        ),
    ]
