# Generated by Django 3.2.12 on 2022-05-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0040_workorder_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='maintenance',
            unique_together={('name', 'type')},
        ),
    ]
