# Generated by Django 3.2.12 on 2022-05-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0041_auto_20220519_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
