# Generated by Django 3.2.12 on 2022-05-19 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_app', '0042_maintenance_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='action',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='cost',
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Quantity')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.maintenance')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
