# Generated by Django 3.2.12 on 2022-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0045_remove_action_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unity',
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('Cm', 'Cm'), ('Kg', 'Kg'), ('Lt', 'Lt'), ('Gb', 'Gb'), ('Mb', 'Mb'), ('Piece', 'Piece'), ('M3', 'M3'), ('Km', 'Km'), ('G', 'G')], default='Piece', max_length=10, verbose_name='Unit'),
        ),
    ]
