# Generated by Django 3.2.12 on 2022-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0046_auto_20220521_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('Cm', 'Cm'), ('Kg', 'Kg'), ('L', 'L'), ('Gb', 'Gb'), ('Mb', 'Mb'), ('Piece', 'Piece'), ('M³', 'M3'), ('Km', 'Km'), ('G', 'G')], default='Piece', max_length=10, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='maintenanceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Quantity'),
        ),
    ]
