# Generated by Django 3.2.12 on 2022-05-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0047_auto_20220522_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name_plural': 'Companies'},
        ),
    ]
