# Generated by Django 3.2.12 on 2022-05-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_app', '0048_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Costumer Name'),
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Costumer, Department, etc', max_length=100, unique=True, verbose_name='Costumer Name')),
                ('parent', models.IntegerField(default=0, help_text='Choose Parent Costumer', verbose_name='Parent Costumer')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contacts', models.CharField(blank=True, max_length=255)),
                ('manager', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='allocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer'),
        ),
        migrations.AlterField(
            model_name='division',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
