# Generated by Django 3.2.12 on 2022-05-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0049_auto_20220526_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='company',
        ),
        migrations.RemoveField(
            model_name='division',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='division',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='position',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='position',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='position',
            name='modified_by',
        ),
        migrations.RenameField(
            model_name='allocation',
            old_name='company',
            new_name='costumer',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='division',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='position',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
