# Generated by Django 3.2.12 on 2022-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0051_auto_20220527_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='is_supplier',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='website',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
