# Generated by Django 3.2.12 on 2022-05-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0052_auto_20220527_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='current_credit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
