# Generated by Django 3.2.12 on 2022-05-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0053_costumer_current_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='telephone',
            new_name='phone',
        ),
    ]
