# Generated by Django 3.2.12 on 2022-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0054_rename_telephone_settings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='credit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='costumer',
            name='debit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
