# Generated by Django 3.2.12 on 2022-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0055_auto_20220531_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='max_debit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
