# Generated by Django 3.2.12 on 2022-05-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0056_costumer_max_debit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='web',
            new_name='website',
        ),
    ]
