# Generated by Django 3.2.12 on 2022-05-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0057_rename_web_settings_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='is_costumer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='is_supplier',
            field=models.IntegerField(default=0),
        ),
    ]
