# Generated by Django 3.2.12 on 2022-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0058_auto_20220531_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='allocation',
        ),
        migrations.AddField(
            model_name='workorder',
            name='component',
            field=models.ManyToManyField(related_name='workorders', to='asset_app.Allocation', verbose_name='Component'),
        ),
    ]
