# Generated by Django 3.2.12 on 2022-06-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0059_auto_20220608_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='component',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='item',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='settings',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='active_status',
            field=models.IntegerField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Finished', 'Finished'), ('Abandoned', 'Abandoned')], default=1, verbose_name='Status'),
        ),
    ]
