# Generated by Django 3.2.12 on 2022-06-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0060_auto_20220609_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='active_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactivated')], default=1, verbose_name='Status'),
        ),
    ]
