# Generated by Django 3.2.12 on 2022-06-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('asset_app', '0062_auto_20220621_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'),
        ),
    ]
