# Generated by Django 3.2.12 on 2022-06-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0063_costumer_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='type',
            field=models.CharField(choices=[('Governmental', 'Governmental'), ('Large Company', 'Large Company'), ('Medium Company', 'Medium Company'), ('Small Company', 'Small Company'), ('Individual Company', 'Individual Company'), ('Other', 'Other')], default='Small Company', max_length=20, verbose_name='Company Type'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='vat',
            field=models.CharField(blank=True, max_length=15, verbose_name='Vat'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='capital',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Capital'),
        ),
    ]
