# Generated by Django 3.2.12 on 2022-06-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0064_auto_20220621_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
