# Generated by Django 3.2.12 on 2022-06-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('asset_app', '0065_rename_zip_code_costumer_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Default Warehouse'),
        ),
    ]
