# Generated by Django 3.2.12 on 2022-06-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0066_alter_costumer_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='max_credit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='max_debit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
    ]
