# Generated by Django 3.2.12 on 2022-06-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0067_auto_20220621_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='image',
            field=models.ImageField(blank=True, default='../media/default.jpg', upload_to='media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(default='../media/default.jpg', upload_to='media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='vat',
            field=models.CharField(blank=True, max_length=15, verbose_name='VAT Number'),
        ),
    ]
