# Generated by Django 3.2.12 on 2022-06-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0068_auto_20220621_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='image',
            field=models.ImageField(blank=True, default='/media/default.jpg', upload_to='media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(default='/media/default.jpg', upload_to='media', verbose_name='Image'),
        ),
    ]
