# Generated by Django 3.2.12 on 2022-05-31 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('isis', '0030_stockmovement'),
        ('asset_app', '0057_rename_web_settings_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('number', models.IntegerField(unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invoice Date')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Due Date')),
                ('paid_status', models.IntegerField(default=0)),
                ('delivered_status', models.IntegerField(default=0)),
                ('finished_status', models.IntegerField(default=0)),
                ('active_status', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, verbose_name='Invoice Notes')),
                ('public_notes', models.TextField(blank=True, verbose_name='Public Notes')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentmethod')),
                ('payment_term', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentterm')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer', verbose_name='Supplier')),
                ('warehouse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.warehouse')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('discount_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('sub_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplierinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.product')),
            ],
        ),
    ]
