# Generated by Django 3.2.12 on 2022-05-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='invoice',
            field=models.CharField(default=0, help_text='Supplier Invoice Number', max_length=100, verbose_name='Invoice Number'),
            preserve_default=False,
        ),
    ]
