# Generated by Django 3.2.12 on 2022-06-01 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('supplier', '0003_alter_supplierinvoice_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'),
        ),
    ]
