# Generated by Django 3.2.12 on 2022-06-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0058_auto_20220531_2233'),
        ('supplier', '0004_alter_supplierinvoice_warehouse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierinvoice',
            unique_together={('invoice', 'supplier')},
        ),
    ]
