BBBB BBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXX XXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXX XXX XXXXXXX XX XX XXXXXXXXXX XX XXXXXX XXXXX XXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXX XXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX X XXXXXX XXXXXXXXX XX XXXX XXXXXXXXXX XXXXXXXXX X XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXX X XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX X XXXXX XXXXXXXXX XXXXXXX XXXXX XXXX XXXXXXX XXXXXXX XXXXX XXXX XXXXXXXXX XXXXXXXXX X XXXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXX XX XXXXXXXX XXX XXXXX XXXXX XXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        BBBBB BBBBB
            XXXXXX X XXXXXXXXX XXXXXXXXXX
        BBBBBBBB BBBBB
    XXXXXXXX

    XXXX XXXXXXX XXXX XXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXX XXXXXX XXX XXX
    XXXXX XXXXXX BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXX XXXXXX XXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXX XXXXX XXXX XXX XXXXXXXXXXX XX XXX XXXXXXX XX XXXXX XXXXXXXX XXX XXXXX XXXXXXX XXX
    XXXX XXXXXXXX XXXXXXXXXXX XX XXXXXXX XXXX XX XXX XXXX XXX XXXX XXX XXXXXXX XXX
    XXXXXXX XX XX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXX X XXXXXXX 
    X
XXXXXXXXX
XXXXXXX

XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXX X XXXXX XXX XXX XXXX XX XXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    
    BBBBB BBBBBBB
    BBBBBBBB BBBBBBB


    BBBBB BBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBB
    BBBBBBBB BBBBBBBBB
    
XXXXXXX

XXXXXXX