BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXX XXXXXXX X XXXXX XXX XXX XXXX XX XXXXXXXXXXXX  XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX
                XXXX XXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX

                XXXX

                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Maintenances') XXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX 
                    XXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Components')  XXXXXXXXXXX
                XXXXX
                
                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Allocations')  XXXXXXXXXXX
                XXXXX

                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Work Orders') XXXXXXXXXXX
                XXXXX
                
                XXXX
                
                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Vendors') XXXXXXXXXXX
                XXXXX
                
                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX 
                    XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Costumers')  XXXXXXXXXXX
                XXXXX

                XXXX

                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Groups')  XXXXXXXXXXX
                XXXXX

                 XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Systems') XXXXXXXXXXX
                XXXXX
                
                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Types')  XXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'SubTypes') XXXXXXX XXXXXXXXXXX
                XXXXX

                XXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Settings') XXXXXXX XXXXXXXXXXX
                XXXXX

            XXXXX

        XXXXXX
        XXXX XXX XXXXXXX XXXXXXXXXX XXX
    XXXXXX
    XXXX XXX XXXXXXX XXXXXXXXX
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXX XXXX XXXXXXX X XXXXX XXX XXX XXXX XX XXXXXXXXXXXX  XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX