# Generated by Django 3.2.12 on 2022-05-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0002_auto_20220523_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='volume_choices',
            new_name='volume_measurements',
        ),
    ]
