# Generated by Django 3.2.12 on 2022-05-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0003_rename_volume_choices_product_volume_measurements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='area_measurements',
            new_name='area_units',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='length_measurements',
            new_name='length_units',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='volume_measurements',
            new_name='volume_units',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight_measurements',
            new_name='weight_units',
        ),
    ]
