# Generated by Django 3.2.12 on 2022-05-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0009_alter_tax_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
