# Generated by Django 3.2.12 on 2022-05-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0010_alter_warehouse_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, unique=True),
        ),
    ]
