# Generated by Django 3.2.12 on 2022-05-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0011_auto_20220524_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parent_product',
            new_name='parent',
        ),
    ]
