# Generated by Django 3.2.12 on 2022-05-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0012_rename_parent_product_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_purchase_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
