# Generated by Django 3.2.12 on 2022-05-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0013_product_max_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='parent_warehouse',
            new_name='parent',
        ),
    ]
