# Generated by Django 3.2.12 on 2022-05-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0015_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_nature',
            field=models.CharField(choices=[('Raw Product', 'Raw Product'), ('Manufactured Product', 'Manufactured Product')], default='Raw Product', max_length=50),
        ),
    ]
