# Generated by Django 3.2.12 on 2022-05-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0017_auto_20220527_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('-name',)},
        ),
        migrations.AddField(
            model_name='documents',
            name='slug',
            field=models.SlugField(default='Recibo', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='Factura', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(default='Factura', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(default='Pagamento', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='slug',
            field=models.SlugField(default='Termos', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='name',
            field=models.CharField(default='Recibo', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='slug',
            field=models.SlugField(default='Recibo', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
