# Generated by Django 3.2.12 on 2022-05-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0018_auto_20220527_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='number',
        ),
        migrations.CreateModel(
            name='ReceiptInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.invoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.receipt')),
            ],
        ),
    ]
