# Generated by Django 3.2.12 on 2022-05-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0019_auto_20220527_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentmethod'),
        ),
    ]
