# Generated by Django 3.2.12 on 2022-05-27 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0051_auto_20220527_0904'),
        ('isis', '0020_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='costumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer', verbose_name='Costumer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.paymentterm'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.warehouse'),
        ),
    ]
