# Generated by Django 3.2.12 on 2022-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0021_auto_20220527_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Invoice Notes'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='public_notes',
            field=models.TextField(blank=True, verbose_name='Public Notes'),
        ),
    ]
