# Generated by Django 3.2.12 on 2022-05-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0023_alter_invoice_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
