# Generated by Django 3.2.12 on 2022-05-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0024_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
