# Generated by Django 3.2.12 on 2022-05-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0025_auto_20220528_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceDetails',
            new_name='InvoiceItem',
        ),
    ]
