# Generated by Django 3.2.12 on 2022-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0026_rename_invoicedetails_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
