# Generated by Django 3.2.12 on 2022-05-29 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0028_auto_20220529_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Due Date'),
        ),
    ]
