# Generated by Django 3.2.12 on 2022-06-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0031_auto_20220601_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
