# Generated by Django 3.2.12 on 2022-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0032_delete_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
