# Generated by Django 3.2.12 on 2022-06-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0033_product_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area_units',
            field=models.CharField(blank=True, choices=[('m2', 'm²'), ('dm2', 'dm²'), ('cm2', 'cm²'), ('mm2', 'mm²'), ('ft2', 'ft²'), ('in2', 'in²')], default='m2', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_units',
            field=models.CharField(blank=True, choices=[('m', 'm'), ('dm', 'dm'), ('cm', 'cm'), ('mm', 'mm'), ('ft', 'ft'), ('in', 'in')], default='m', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_nature',
            field=models.CharField(blank=True, choices=[('Raw Product', 'Raw Product'), ('Manufactured Product', 'Manufactured Product')], default='Raw Product', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_units',
            field=models.CharField(blank=True, choices=[('m3', 'm³'), ('dm3', 'dm³'), ('cm3', 'cm³'), ('mm3', 'mm³'), ('ft3', 'ft³'), ('in3', 'in³'), ('litre', 'litre'), ('gallon', 'gallon')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_units',
            field=models.CharField(blank=True, choices=[('kg', 'Kg'), ('g', 'G'), ('mg', 'MG'), ('ounce', 'ounce'), ('pound', 'pound'), ('ton', 'ton')], default='kg', max_length=50),
        ),
    ]
