# Generated by Django 3.2.12 on 2022-06-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0035_auto_20220621_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categori',
        ),
    ]
