# Generated by Django 3.2.12 on 2022-06-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0036_rename_category_product_categori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categori',
            new_name='category',
        ),
    ]
