# Generated by Django 3.2.12 on 2022-06-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0037_rename_categori_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
