# Generated by Django 3.2.12 on 2022-06-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0043_auto_20220622_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
    ]
