# Generated by Django 3.2.12 on 2022-06-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0069_auto_20220622_0059'),
        ('isis', '0044_remove_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='costumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset_app.costumer'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.receipt')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, default='/media/default.jpg', upload_to='media', verbose_name='Primary Image')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.receipt')),
            ],
        ),
    ]
