# Generated by Django 3.2.12 on 2022-06-26 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0045_auto_20220622_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 7, 51, 19, 728064), verbose_name='Due Date'),
        ),
    ]
