# Generated by Django 3.2.12 on 2022-06-26 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0046_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='debit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 10, 32, 6, 252197), verbose_name='Due Date'),
        ),
    ]
