# Generated by Django 3.2.12 on 2022-06-26 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0047_auto_20220626_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 10, 36, 34, 263722), verbose_name='Due Date'),
        ),
    ]
