# Generated by Django 3.2.12 on 2022-06-27 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0049_auto_20220626_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 13, 5, 46, 631945), verbose_name='Due Date'),
        ),
    ]
