# Generated by Django 3.2.12 on 2022-06-27 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0050_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 14, 2, 32, 989963), verbose_name='Due Date'),
        ),
    ]
