# Generated by Django 3.2.12 on 2022-06-27 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0051_auto_20220627_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 17, 54, 44, 913344), verbose_name='Due Date'),
        ),
    ]
