# Generated by Django 3.2.12 on 2022-06-29 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0053_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 18, 24, 12, 668868), verbose_name='Due Date'),
        ),
    ]
