# Generated by Django 3.2.12 on 2022-06-29 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0054_auto_20220629_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptinvoice',
            old_name='total',
            new_name='remaining',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 21, 16, 52, 968503), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='active_status',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
