# Generated by Django 3.2.12 on 2022-06-30 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0055_auto_20220629_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptinvoice',
            name='debit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 8, 35, 17, 63929), verbose_name='Due Date'),
        ),
    ]
