# Generated by Django 3.2.12 on 2022-06-30 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0058_auto_20220630_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='finished_status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 11, 22, 8, 909592), verbose_name='Due Date'),
        ),
    ]
