# Generated by Django 3.2.12 on 2022-07-03 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0062_auto_20220703_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.FileField(blank=True, default='document_template.html', upload_to='media', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.ImageField(blank=True, default='/media/default.jpg', upload_to='media', verbose_name='Add File'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 14, 51, 13, 943255), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 14, 51, 13, 938246), verbose_name='Due Date'),
        ),
    ]
