# Generated by Django 3.2.12 on 2022-07-03 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0064_auto_20220703_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='short_name',
            field=models.CharField(default=models.CharField(max_length=20, unique=True), max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 16, 15, 38, 817976), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 16, 15, 38, 802354), verbose_name='Due Date'),
        ),
    ]
