# Generated by Django 3.2.12 on 2022-07-03 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0065_auto_20220703_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 16, 16, 18, 752843), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 16, 16, 18, 742817), verbose_name='Due Date'),
        ),
    ]
