# Generated by Django 3.2.12 on 2022-07-03 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0067_auto_20220703_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='short_name',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 17, 50, 52, 160244), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 17, 50, 52, 143188), verbose_name='Due Date'),
        ),
    ]
