# Generated by Django 3.2.12 on 2022-07-04 07:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0071_auto_20220703_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 7, 59, 3, 659703), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 7, 59, 3, 659703), verbose_name='Due Date'),
        ),
        migrations.CreateModel(
            name='InvoicingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('discount_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('sub_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('invoicing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.invoicing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isis.product')),
            ],
        ),
    ]
