# Generated by Django 3.2.12 on 2022-07-04 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0074_auto_20220704_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicing',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isis.document', verbose_name='Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 14, 0, 54, 473525), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 14, 0, 54, 470481), verbose_name='Due Date'),
        ),
    ]
