# Generated by Django 3.2.12 on 2022-07-05 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isis', '0080_auto_20220705_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='default',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='default',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='documentpayment',
            name='file',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Add File'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 21, 44, 46, 172219), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoicing',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 21, 44, 46, 169197), verbose_name='Due Date'),
        ),
    ]
